export const chordPracticeResources = {
  'zh-CN': {
    title: '和弦练习', category: '和弦与转位', selectTitle: '选择和弦练习方式', selectHelp: '根据你的目标，选择更适合的练习模式。',
    helpOpen: '查看和弦练习方式说明', helpClose: '关闭练习方式说明', helpTitle: '练习方式说明', understood: '知道了',
    recommended: '推荐', learning: '学习模式', review: '综合复习',
    modes: { sequential: '循序练习', comprehensive: '综合随机' },
    sequentialDescription: '围绕单一大调，逐步扩展练习内容', sequentialSuitable: '适合记忆和弦构成、转位与调内和弦关系', sequentialPath: '三和弦 → 七和弦 → 转位',
    mixedDescription: '从完整和弦范围中综合随机出题', mixedSuitable: '适合复习、巩固与检验整体反应能力', mixedPath: '根音 · 和弦类型 · 转位综合混合',
    sequentialHelp: '每次练习只围绕一个大调的 7 个调内和弦出题。当前调由你选择，练习过程中不会自动切换到其他调。',
    questionRange: '{{from}} / {{to}} 题', scope10: '仅练习调内三和弦原位', scope50: '加入调内七和弦原位', scope100: '进一步加入三和弦转位',
    scopeEndless: '加入三和弦与七和弦的全部转位，并持续围绕当前调练习，直到手动结束',
    balancedHelp: '题目采用均衡题袋方式安排，尽量让当前范围内的和弦获得均匀练习机会。',
    mixedHelp: '从完整和弦范围中综合随机出题，覆盖不同根音、和弦类型与转位。',
    mixedHelpMore: '它不会限制在单一大调内，适合已经熟悉基础内容后进行综合复习与反应训练。',
    settings: '练习设置', closeSettings: '关闭练习设置', currentKey: '当前调', nextSession: '新练习开始时生效',
    previousKey: '上一个大调', nextKey: '下一个大调', selectKey: '选择循序练习当前调', majorKey: '{{tonic}} 大调',
    questionCount: '题数', countHelp: '选择本轮练习题量', countAria: '和弦练习题数', endless: '无限', questions: '{{count}}题',
    showTones: '显示构成音', tonesHelp: '按当前转位顺序显示', tonesOn: '显示构成音已开启', tonesOff: '显示构成音已关闭',
    training: '本次训练', fullRange: '完整随机范围', countScope: '题数决定循序范围', triadsSevenths: '三和弦 + 七和弦', balanced: '均衡题袋',
    allInversions: '全部转位', randomRegister: '随机音区', phaseOrder: '分解 + 柱式',
    settingsNote: '题数和当前调将在下一轮练习开始时生效；构成音显示立即生效。',
    backPractice: '返回练习', pause: '暂停', resume: '继续', end: '结束', endSave: '结束并保存', done: '完成',
    fontFailed: '本地音乐字体加载失败。', currentChord: '当前和弦', preparing: '正在准备', tones: ' · 构成音：{{notes}}',
    inversions: { 0: '原位', 1: '第一转位', 2: '第二转位', 3: '第三转位' },
    questionLabel: '{{root}} {{chordName}} · {{inversion}}', staffLabel: '{{symbol}}：左侧分解和弦，右侧柱式和弦',
    arpeggio: '分解', block: '柱式', arpeggioTerm: '琶音', blockTerm: '柱式和弦',
    group: { completed: '已完成', wrong: '需重试', active: '当前', secondary: '稍后' },
    stages: { arpeggio: '分解', transition: '过渡', block: '柱式', complete: '完成' },
    currentStage: '当前阶段 · {{stage}}',
    prompts: { arpeggio: '请按谱面顺序弹奏分解和弦', block: '请弹奏柱式和弦', arpeggioWrong: '松开琴键后从分解第一个音重新开始', blockWrong: '柱式错误 · 松开琴键后从分解重新开始', arpeggioRelease: '分解完成 · 请松开琴键', blockRelease: '柱式完成 · 请松开琴键', correct: '正确', complete: '本轮练习完成' },
    paused: '练习已暂停', disconnected: 'MIDI 已断开，练习已安全暂停', releaseResume: '请先松开琴键以继续',
    progress: '进度', currentQuestion: '当前题目', completedCount: '已完成 {{count}}', sessionStatus: '本轮状态', streak: '连续正确 {{count}}',
    reportTitle: '和弦练习报告', unavailable: '记录不可用', unavailableHelp: '这条练习记录无法读取。', backHistory: '返回记录', journal: '练习记录',
    savedFacts: '以下内容来自本轮已保存的练习事实。', overview: '本轮概览', result: '练习结果',
    firstPassHelp: '分解与柱式均首次成功，才计为首次通过。', factCounts: '事实计数', errors: '错误分布', median: '中位数', timing: '演奏时间', completedSamples: '按已完成题目汇总',
    snapshot: '历史快照', sessionInfo: '本轮信息',
    metrics: { completed: '完成', firstPass: '首次通过', firstPassRate: '完成率', totalErrors: '总错误', longestStreak: '最长连对', duration: '练习时长', arpeggioErrors: '分解错误', blockErrors: '柱式错误' },
    timingLabels: { questionStartLatencyMs: '开始弹奏用时', arpeggioDurationMs: '分解弹奏用时', switchToBlockLatencyMs: '切换柱式用时', blockLandingSpreadMs: '同时落键差' },
    seconds: '{{seconds}} 秒', samples: '{{count}} 个样本',
    sessionLabels: { mode: '练习模式', key: '调性', count: '题数', outcome: '练习结果', start: '开始时间', end: '结束时间' },
    status: { completed: '已完成', stopped: '中途结束', manual: '手动结束' },
    modeWithKey: '{{mode}} · {{key}}', badge: '和弦', openReport: '打开{{summary}}练习报告',
    recordCompleted: '完成 {{completed}}/{{total}}', recordEndless: '完成 {{count}}', recordFacts: '{{completed}} · 错误 {{errors}} · 练习时长 {{duration}}',
    saveFailed: '练习已结束，但记录保存失败。', saveFailedHelp: '和弦练习结果没有被加入练习记录。', readFailed: '暂时无法读取和弦练习记录。', readFailedHelp: '其他练习功能仍可正常使用。'
  },
  en: {
    title: 'Chord Practice', category: 'Chords & Inversions', selectTitle: 'Choose your chord practice mode', selectHelp: 'Choose the practice mode that fits your goal.',
    helpOpen: 'About chord practice modes', helpClose: 'Close practice mode help', helpTitle: 'Practice modes', understood: 'Got it',
    recommended: 'Recommended', learning: 'Learning mode', review: 'Mixed review',
    modes: { sequential: 'Progressive practice', comprehensive: 'Mixed practice' },
    sequentialDescription: 'Build your practice step by step within one major key', sequentialSuitable: 'Learn chord tones, inversions and relationships within a key', sequentialPath: 'Triads → Seventh chords → Inversions',
    mixedDescription: 'Random questions from the full chord range', mixedSuitable: 'Review, consolidate and test your overall response', mixedPath: 'Roots · Chord types · Inversions',
    sequentialHelp: 'Each session uses the seven diatonic chords of one major key. You choose the key; it does not change automatically during practice.',
    questionRange: '{{from}} / {{to}} questions', scope10: 'Diatonic triads in root position only', scope50: 'Adds diatonic seventh chords in root position', scope100: 'Also adds triad inversions',
    scopeEndless: 'Includes all triad and seventh-chord inversions in the chosen key until you end the session',
    balancedHelp: 'Balanced question bags give the chords in the selected range even practice opportunities.',
    mixedHelp: 'Random questions cover different roots, chord types and inversions across the full chord range.',
    mixedHelpMore: 'This mode is not limited to one major key. Use it for review and response training once you know the basics.',
    settings: 'Practice settings', closeSettings: 'Close practice settings', currentKey: 'Current key', nextSession: 'Applies when a new session starts',
    previousKey: 'Previous major key', nextKey: 'Next major key', selectKey: 'Choose the key for progressive practice', majorKey: '{{tonic}} Major',
    questionCount: 'Questions', countHelp: 'Choose the number of questions for this session', countAria: 'Chord practice question count', endless: 'Endless',
    questions_one: '{{count}} question', questions_other: '{{count}} questions',
    showTones: 'Show chord tones', tonesHelp: 'Shown in the current inversion order', tonesOn: 'Show chord tones: on', tonesOff: 'Show chord tones: off',
    training: 'This session', fullRange: 'Full random range', countScope: 'Question count sets the progressive range', triadsSevenths: 'Triads + Seventh chords', balanced: 'Balanced question bags',
    allInversions: 'All inversions', randomRegister: 'Random register', phaseOrder: 'Arpeggio + Block chord',
    settingsNote: 'Question count and key apply to the next session; chord-tone visibility applies immediately.',
    backPractice: 'Back to practice', pause: 'Pause', resume: 'Resume', end: 'End', endSave: 'End and save', done: 'Done',
    fontFailed: 'The local music font could not be loaded.', currentChord: 'Current chord', preparing: 'Preparing', tones: ' · Chord tones: {{notes}}',
    inversions: { 0: 'Root position', 1: 'First inversion', 2: 'Second inversion', 3: 'Third inversion' },
    questionLabel: '{{root}} {{chordName}} · {{inversion}}', staffLabel: '{{symbol}}: arpeggio on the left, block chord on the right',
    arpeggio: 'Arpeggio', block: 'Block chord', arpeggioTerm: 'Arpeggio', blockTerm: 'Block chord',
    group: { completed: 'Completed', wrong: 'Try again', active: 'Current', secondary: 'Later' },
    stages: { arpeggio: 'Arpeggio', transition: 'Transition', block: 'Block chord', complete: 'Complete' },
    currentStage: 'Current stage · {{stage}}',
    prompts: { arpeggio: 'Play the arpeggio in the order shown', block: 'Play the block chord', arpeggioWrong: 'Release the keys, then restart from the first arpeggio note', blockWrong: 'Incorrect block chord. Release the keys, then restart the arpeggio', arpeggioRelease: 'Arpeggio complete · Release the keys', blockRelease: 'Block chord complete · Release the keys', correct: 'Correct', complete: 'Session complete' },
    paused: 'Practice paused', disconnected: 'MIDI disconnected. Practice is safely paused.', releaseResume: 'Release the keys before resuming',
    progress: 'Progress', currentQuestion: 'Current question', completedCount_one: '{{count}} completed', completedCount_other: '{{count}} completed', sessionStatus: 'Session status', streak_one: '{{count}} first-pass success in a row', streak_other: '{{count}} first-pass successes in a row',
    reportTitle: 'Chord Practice report', unavailable: 'Record unavailable', unavailableHelp: 'This practice record could not be read.', backHistory: 'Back to history', journal: 'Practice history',
    savedFacts: 'These are the saved facts from this practice session.', overview: 'Session overview', result: 'Practice result',
    firstPassHelp: 'A question passes on the first attempt only if both the arpeggio and block chord succeed without errors.', factCounts: 'Error counts', errors: 'Error distribution', median: 'Median', timing: 'Playing time', completedSamples: 'Summarized from completed questions',
    snapshot: 'Saved snapshot', sessionInfo: 'Session information',
    metrics: { completed: 'Completed', firstPass: 'First-pass successes', firstPassRate: 'First-pass success rate', totalErrors: 'Total errors', longestStreak: 'Longest first-pass streak', duration: 'Practice duration', arpeggioErrors: 'Arpeggio errors', blockErrors: 'Block chord errors' },
    timingLabels: { questionStartLatencyMs: 'Time to start playing', arpeggioDurationMs: 'Arpeggio duration', switchToBlockLatencyMs: 'Time to switch to block chord', blockLandingSpreadMs: 'Key landing spread' },
    seconds: '{{seconds}} s', samples_one: '{{count}} sample', samples_other: '{{count}} samples',
    sessionLabels: { mode: 'Practice mode', key: 'Key', count: 'Questions', outcome: 'Practice result', start: 'Started', end: 'Ended' },
    status: { completed: 'Completed', stopped: 'Ended early', manual: 'Ended manually' },
    modeWithKey: '{{mode}} · {{key}}', badge: 'Chords', openReport: 'Open practice report: {{summary}}',
    recordCompleted: 'Completed {{completed}}/{{total}}', recordEndless_one: '{{count}} completed', recordEndless_other: '{{count}} completed', recordFacts: '{{completed}} · Errors {{errors}} · Practice duration {{duration}}',
    saveFailed: 'Practice ended, but the record could not be saved.', saveFailedHelp: 'The Chord Practice result was not added to history.', readFailed: 'Chord Practice history could not be read.', readFailedHelp: 'Other practice features are still available.'
  }
} as const
