/** Only existing Interval flow and necessary shared History chrome. No durable values. */
export const intervalFlowResources = {
  'zh-CN': {
    preparing: '正在准备音程练习…', activePrompt: '请按出以 {{bassNote}} 为低音的{{intervalName}}音程',
    notationBass: '{{intervalName}}：低音 {{bassNote}}', notationPair: '{{intervalName}}：{{bassNote}} 与 {{targetNote}}',
    progressFixed: '已完成 {{completed}} / {{total}}', progressEndless: '已完成 {{completed}}',
    midiPaused: 'MIDI 已断开，练习已安全暂停', paused: '练习已暂停', receiving: '正在接收弹奏…',
    wrongRelease: '错误，请松开全部按键后重试原题', correctRelease: '正确，请松开全部按键', correct: '正确',
    backPractice: '返回练习', pause: '暂停', resume: '继续', endEarly: '提前结束', notation: '音程谱面',
    endTitle: '结束本轮？', endFixed: '已完成 {{completed}} / {{total}}。结束后，本轮结果会保存到练习记录。',
    endEndless: '已完成 {{count}} 题。结束后，本轮结果会保存到练习记录。',
    continuePractice: '继续练习', endViewResult: '结束并查看结果',
    overview: '本轮概览', result: '练习结果', completedQuestions: '完成题数', firstTryAccuracy: '首次正确率',
    retriedCorrect: '重试后答对', wrongAttempts: '错误尝试', accuracyExplanation: '首次正确率只统计未发生完整错误尝试便答对的题目。',
    learningFocus: '学习重点', difficultIntervals: '易错音程', noData: '暂无数据', noDifficult: '本轮没有明显易错音程',
    difficultSummary: '首次失误 {{misses}} 题 · 错误尝试 {{attempts}} 次',
    categoryStats: '分类统计', performance: '本轮音程表现', presentedOnly: '仅显示本轮出现过的音程',
    presented: '出现 {{count}} 次', firstTryCorrect: '首次正确 {{count}}', retriedStat: '重试后正确 {{count}}', wrongStat: '错误尝试 {{count}}',
    snapshot: '历史快照', sessionSettings: '本轮设置', fixedQuestions: '固定 {{count}} 题',
    practiceCompleted: '练习完成', sessionEnded: '本轮已结束', resultTitle: '音程练习结果',
    completedDescription: '已完成本轮设定题数。', stoppedDescription: '已保存本轮真正完成的题目与统计。',
    completed: '已完成', again: '再练一轮', viewHistory: '查看练习记录', reportTitle: '音程练习报告',
    unavailable: '记录不可用', unavailableDescription: '这条练习记录无法读取。', backHistory: '返回记录',
    historyTitle: '练习记录', savedFacts: '以下内容来自本轮已保存的练习事实。', intervalBadge: '音程', openReport: '打开{{module}}练习报告',
    recordCompletedFixed: '完成 {{completed}}/{{total}}', recordCompletedEndless: '完成 {{count}} 题',
    recordSummary: '{{progress}} · 重试后答对 {{retried}} · 错误尝试 {{wrong}}',
    saveFailed: '练习已结束，但记录保存失败。', saveFailedDetail: '音程练习结果仍保留，可重试写入此设备。',
    readFailed: '暂时无法读取音程练习记录。', readFailedDetail: '其他练习功能仍可正常使用。', retry: '重试',
    syncing: '正在同步本地记录', recordsError: '共 {{count}} 条 · 读取异常', recordsWarning: '共 {{count}} 条 · 部分记录不可用', recordsCount: '共 {{count}} 条记录',
    emptyInterval: '暂无音程练习记录', emptyChord: '暂无和弦练习记录', emptySight: '暂无识谱练习记录', emptyAll: '暂无练习记录',
    emptyIntervalDetail: '完成音程练习后，结果会显示在这里。', emptyChordDetail: '完成和弦练习后，记录会显示在这里。',
    emptySightDetail: '完成一轮识谱练习后，结果会显示在这里。', emptyAllDetail: '完成一轮练习后，结果会显示在这里。',
    savedSessions: '这里保存着 {{count}} 次练习。', journalEmpty: '完成一次练习后，这里会留下你的进步。',
    summary: '练习汇总', savedPractice: '已保存练习', sessionsUnit: '次', modulesCaption: '识谱、和弦与音程练习记录',
    streak: '连续练习天数', daysUnit: '天', localDates: '按本地日期统计', totalQuestions: '累计完成题数', questionsUnit: '题', savedCaption: '包含已保存的练习',
    recent: '最近练习记录', filterLabel: '练习模块筛选', all: '全部', sightBadge: '识谱', chordBadge: '和弦',
    reading: '正在读取本地记录…', historyReadFailed: '暂时无法读取练习记录', preservedData: '已保存的数据不会被替换；稍后重新进入记录页可再次读取。',
    trend: '练习趋势', rangeLabel: '趋势时间范围', last7: '近7天', last30: '近30天', trendAria: '按本地自然日统计的练习趋势', trendEmpty: '当前范围内暂无练习记录',
    trendQuestions: '完成题数', trendSessions: '练习次数',
    trendAll: '展示识谱与和弦的练习次数和完成题数，并包含音程练习。', trendSight: '当前仅显示识谱练习活动量。',
    trendChord: '当前仅显示和弦练习活动量。', trendInterval: '当前仅显示音程练习活动量。'
  },
  en: {
    preparing: 'Preparing interval practice…', activePrompt: 'Play the {{intervalName}} with {{bassNote}} as the bass note',
    notationBass: '{{intervalName}}: bass note {{bassNote}}', notationPair: '{{intervalName}}: {{bassNote}} and {{targetNote}}',
    progressFixed: 'Completed {{completed}} / {{total}}', progressEndless: 'Completed {{completed}}',
    midiPaused: 'MIDI disconnected. Practice is safely paused.', paused: 'Practice paused', receiving: 'Receiving your notes…',
    wrongRelease: 'Incorrect. Release all keys to retry the same question.', correctRelease: 'Correct. Release all keys.', correct: 'Correct',
    backPractice: 'Back to practice', pause: 'Pause', resume: 'Resume', endEarly: 'End early', notation: 'Interval notation',
    endTitle: 'End this session?', endFixed: 'Completed {{completed}} / {{total}}. Ending saves this session’s results to practice history.',
    endEndless_one: 'Completed {{count}} question. Ending saves this session’s results to practice history.',
    endEndless_other: 'Completed {{count}} questions. Ending saves this session’s results to practice history.',
    continuePractice: 'Continue practice', endViewResult: 'End and view results',
    overview: 'Session overview', result: 'Practice results', completedQuestions: 'Completed questions', firstTryAccuracy: 'First-attempt accuracy',
    retriedCorrect: 'Correct after retry', wrongAttempts: 'Incorrect attempts', accuracyExplanation: 'First-attempt accuracy counts questions answered correctly without a complete incorrect attempt.',
    learningFocus: 'Learning focus', difficultIntervals: 'Challenging intervals', noData: 'No data', noDifficult: 'No notably challenging intervals this session',
    difficultSummary: 'First-attempt misses: {{misses}} · Incorrect attempts: {{attempts}}',
    categoryStats: 'By interval', performance: 'Interval performance this session', presentedOnly: 'Only intervals presented this session',
    presented_one: 'Presented {{count}} time', presented_other: 'Presented {{count}} times', firstTryCorrect: 'Correct on first attempt: {{count}}',
    retriedStat: 'Correct after retry: {{count}}', wrongStat: 'Incorrect attempts: {{count}}',
    snapshot: 'Saved snapshot', sessionSettings: 'Session settings', fixedQuestions_one: 'Fixed: {{count}} question', fixedQuestions_other: 'Fixed: {{count}} questions',
    practiceCompleted: 'Practice complete', sessionEnded: 'Session ended', resultTitle: 'Interval practice results',
    completedDescription: 'All configured questions are complete.', stoppedDescription: 'Completed questions and their statistics have been saved.',
    completed: 'Completed', again: 'Practice again', viewHistory: 'View practice history', reportTitle: 'Interval practice report',
    unavailable: 'Record unavailable', unavailableDescription: 'This practice record cannot be read.', backHistory: 'Back to history',
    historyTitle: 'Practice history', savedFacts: 'These results come from the saved facts of this session.', intervalBadge: 'Interval', openReport: 'Open {{module}} report',
    recordCompletedFixed: 'Completed {{completed}}/{{total}}', recordCompletedEndless_one: 'Completed {{count}} question', recordCompletedEndless_other: 'Completed {{count}} questions',
    recordSummary: '{{progress}} · Correct after retry: {{retried}} · Incorrect attempts: {{wrong}}',
    saveFailed: 'Practice ended, but the record could not be saved.', saveFailedDetail: 'Your interval results are retained. Retry saving them to this device.',
    readFailed: 'Interval practice records could not be read.', readFailedDetail: 'Other practice features remain available.', retry: 'Retry',
    syncing: 'Syncing local records', recordsError_one: '{{count}} record · Read error', recordsError_other: '{{count}} records · Read error',
    recordsWarning_one: '{{count}} record · Some records unavailable', recordsWarning_other: '{{count}} records · Some records unavailable',
    recordsCount_one: '{{count}} record', recordsCount_other: '{{count}} records',
    emptyInterval: 'No interval practice records yet', emptyChord: 'No chord practice records yet', emptySight: 'No sight-reading records yet', emptyAll: 'No practice records yet',
    emptyIntervalDetail: 'Complete interval practice to see your results here.', emptyChordDetail: 'Complete chord practice to see your records here.',
    emptySightDetail: 'Complete a sight-reading session to see your results here.', emptyAllDetail: 'Complete a practice session to see your results here.',
    savedSessions_one: '{{count}} practice session saved here.', savedSessions_other: '{{count}} practice sessions saved here.', journalEmpty: 'Complete a practice session to start recording your progress.',
    summary: 'Practice summary', savedPractice: 'Saved sessions', sessionsUnit_one: 'session', sessionsUnit_other: 'sessions', modulesCaption: 'Sight-reading, chord and interval practice records',
    streak: 'Practice streak', daysUnit_one: 'day', daysUnit_other: 'days', localDates: 'Based on local dates', totalQuestions: 'Total completed questions', questionsUnit_one: 'question', questionsUnit_other: 'questions', savedCaption: 'Includes saved practice sessions',
    recent: 'Recent practice', filterLabel: 'Filter practice modules', all: 'All', sightBadge: 'Sight reading', chordBadge: 'Chord',
    reading: 'Reading local records…', historyReadFailed: 'Practice records could not be read', preservedData: 'Saved data will not be replaced. Return to history later to try reading again.',
    trend: 'Practice trend', rangeLabel: 'Trend date range', last7: 'Last 7 days', last30: 'Last 30 days', trendAria: 'Practice activity by local calendar day', trendEmpty: 'No practice records in this date range',
    trendQuestions: 'Completed questions', trendSessions: 'Practice sessions',
    trendAll: 'Shows practice sessions and completed questions for sight reading, chords and intervals.', trendSight: 'Shows sight-reading activity only.',
    trendChord: 'Shows chord practice activity only.', trendInterval: 'Shows interval practice activity only.'
  }
} as const
