export const sightReadingResources = {
  'zh-CN': {
    title: '识谱练习', preview: '练习预览', previewTitle: '{{staff}}识谱', previewNotation: '{{staff}}练习预览', ready: '准备就绪',
    settings: '识谱练习设置', closeSettings: '关闭识谱练习设置', nextSession: '下一轮生效', sessionSettings: '本轮设置',
    staff: '谱表', defaultStaff: '默认谱表', staffHelp: '高音谱表、低音谱表或大谱表',
    staffs: { treble: '高音谱表', bass: '低音谱表', grand: '大谱表' },
    key: '调性', keyHelp: '支持现有 15 个大调', majorKey: '{{tonic}} 大调',
    noteCount: '音符数量', noteCountHelp: '单音保持原有首音判定；双音使用 150ms 同时音捕获',
    modes: { single: '单音', double: '双音' },
    notePool: '音符内容', notePoolHelp: '调内音或包含临时变音', doublePool: '双音固定调内',
    pools: { diatonic: '调内音', chromatic: '含临时变音' },
    questionCount: '题数', defaultQuestionCount: '默认题数', questionCountHelp: '10、20、50 或 100 题',
    timeLimit: '每题时限', timeHelp: '当前模式固定为 {{count}} 秒', seconds: '{{count}} 秒', fixedSeconds: '固定 {{count}} 秒',
    noteNames: '显示音名', namesVisibleHelp: '答题前显示目标音名', namesHiddenHelp: '答题前不显示目标音名',
    namesVisible: '显示音名已开启', namesHidden: '显示音名已关闭', visibleSummary: '显示音名', hiddenSummary: '隐藏音名',
    singleQuestions: '{{count}} 个音符', pairQuestions: '{{count}} 道双音题',
    connectedHelp: '{{device}}，可以直接弹奏目标音。', connectHelp: '开始前请打开 MIDI 页面，连接 MIDI 设备。', start: '开始练习',
    end: '结束本轮', question: '第 {{index}} 题', remainingTime: '本题剩余时间', pause: '暂停', resume: '继续', waitingMidi: '等待 MIDI',
    paused: '已暂停', pausedPrompt: '练习已暂停', disconnectedPrompt: 'MIDI 已断开，练习已安全暂停', recoveredPrompt: 'MIDI 已恢复，请点击继续',
    reconnectHelp: '重新连接后再继续', recoveredHelp: '连接已恢复，需明确继续',
    playSingle: '请弹出这个音', playPair: '请弹出这两个音', correctSingle: '回答正确', wrongSingle: '这次弹错了', timeoutSingle: '本题超时',
    correctPair: '正确 · {{intervalName}}', wrongPair: '错误 · 目标：{{intervalName}}', timeoutPair: '超时 · 目标：{{intervalName}}',
    wrongNotes: '目标 {{target}} · 弹成 {{input}}', timeoutNotes: '本题超时 · {{target}}', currentQuestion: '当前识谱题目', questionNotes: '当前题目 {{target}}',
    completed: '完成', correct: '正确', wrong: '错误', timeout: '超时', currentStreak: '当前连对', accuracy: '正确率',
    endTitle: '结束本轮？', endProgress: '已完成 {{completed}} / {{total}}。', endHelp: '结束后，已完成部分会保存到此设备。', continuePractice: '继续练习', endSave: '结束并保存',
    resultTitle: '本轮完成', result: '识谱练习结果', resultAccuracy: '本轮正确率 {{accuracy}}%，', errorHeadline: '再留意这个易错音。',
    resultFinished: '本轮练习已完成，', noErrorHeadline: '没有需要优先处理的音符错误。',
    resultSummary: '{{staff}} · {{key}} · {{count}} 题 · 固定 {{seconds}} 秒',
    averageReaction: '平均反应', bestStreak: '最高连对', reactionTime: '{{seconds}} 秒', attention: '本轮最需留意',
    errorCount: '这个目标音在本轮出现了 {{count}} 次错误或超时。', noErrors: '本轮没有发现需要优先处理的目标音。', again: '再练一轮', done: '完成',
    historyModule: '识谱', completedStatus: '已完成', stoppedStatus: '提前结束', historyTitle: '{{staff}} · {{key}}', historySettings: '{{pool}} · {{names}}',
    historyFacts: '{{settings}} · 完成 {{completed}}/{{total}} · 正确 {{correct}} / 错误 {{wrong}} / 超时 {{timeout}} · {{duration}}',
    durationSeconds: '{{count}} 秒', durationMinutes: '{{count}} 分 {{seconds}} 秒',
    saveFailed: '本地保存失败', saveFailedHelp: '当前练习事实仍保留，可重试写入此设备。', retry: '重试'
  },
  en: {
    title: 'Sight Reading', preview: 'Practice preview', previewTitle: '{{staff}} sight reading', previewNotation: '{{staff}} practice preview', ready: 'Ready',
    settings: 'Sight Reading settings', closeSettings: 'Close Sight Reading settings', nextSession: 'Applies to the next session', sessionSettings: 'Session settings',
    staff: 'Staff', defaultStaff: 'Default staff', staffHelp: 'Treble staff, bass staff or grand staff',
    staffs: { treble: 'Treble staff', bass: 'Bass staff', grand: 'Grand staff' },
    key: 'Key', keyHelp: 'Supports the existing 15 major keys', majorKey: '{{tonic}} Major',
    noteCount: 'Note count', noteCountHelp: 'Single notes use the first played note; note pairs use a 150 ms simultaneous-note capture window',
    modes: { single: 'Single notes', double: 'Note pairs' },
    notePool: 'Note pool', notePoolHelp: 'Diatonic notes or notes with accidentals', doublePool: 'Note pairs are always diatonic',
    pools: { diatonic: 'Diatonic notes', chromatic: 'With accidentals' },
    questionCount: 'Questions', defaultQuestionCount: 'Default question count', questionCountHelp: '10, 20, 50 or 100 questions',
    timeLimit: 'Time per question', timeHelp_one: 'This mode is fixed at {{count}} second', timeHelp_other: 'This mode is fixed at {{count}} seconds',
    seconds_one: '{{count}} second', seconds_other: '{{count}} seconds', fixedSeconds_one: 'Fixed at {{count}} second', fixedSeconds_other: 'Fixed at {{count}} seconds',
    noteNames: 'Show note names', namesVisibleHelp: 'Show target note names before answering', namesHiddenHelp: 'Hide target note names before answering',
    namesVisible: 'Show note names: on', namesHidden: 'Show note names: off', visibleSummary: 'Note names shown', hiddenSummary: 'Note names hidden',
    singleQuestions_one: '{{count}} note', singleQuestions_other: '{{count}} notes', pairQuestions_one: '{{count}} note-pair question', pairQuestions_other: '{{count}} note-pair questions',
    connectedHelp: '{{device}}. You can play the target notes directly.', connectHelp: 'Open the MIDI page and connect your MIDI device before starting.', start: 'Start practice',
    end: 'End practice', question: 'Question {{index}}', remainingTime: 'Time remaining for this question', pause: 'Pause', resume: 'Resume', waitingMidi: 'Waiting for MIDI',
    paused: 'Paused', pausedPrompt: 'Practice paused', disconnectedPrompt: 'MIDI disconnected. Practice is safely paused.', recoveredPrompt: 'MIDI reconnected. Select Resume to continue.',
    reconnectHelp: 'Reconnect before resuming', recoveredHelp: 'Reconnected. Resume explicitly to continue.',
    playSingle: 'Play this note', playPair: 'Play these two notes', correctSingle: 'Correct', wrongSingle: 'Incorrect note', timeoutSingle: 'Time expired',
    correctPair: 'Correct · {{intervalName}}', wrongPair: 'Incorrect · Target: {{intervalName}}', timeoutPair: 'Time expired · Target: {{intervalName}}',
    wrongNotes: 'Target {{target}} · Played {{input}}', timeoutNotes: 'Time expired · {{target}}', currentQuestion: 'Current sight-reading question', questionNotes: 'Current question {{target}}',
    completed: 'Completed', correct: 'Correct', wrong: 'Wrong', timeout: 'Timeout', currentStreak: 'Current streak', accuracy: 'Accuracy',
    endTitle: 'End this session?', endProgress: 'Completed {{completed}} / {{total}}.', endHelp: 'Completed questions will be saved on this device.', continuePractice: 'Continue practice', endSave: 'End and save',
    resultTitle: 'Session complete', result: 'Sight Reading result', resultAccuracy: 'Your accuracy was {{accuracy}}%.', errorHeadline: 'Give this missed note another look.',
    resultFinished: 'This practice session is complete.', noErrorHeadline: 'No note errors need priority attention.',
    resultSummary_one: '{{staff}} · {{key}} · {{count}} question · Fixed at {{seconds}} seconds', resultSummary_other: '{{staff}} · {{key}} · {{count}} questions · Fixed at {{seconds}} seconds',
    averageReaction: 'Average response', bestStreak: 'Best streak', reactionTime: '{{seconds}} s', attention: 'Note to focus on',
    errorCount_one: 'This target note had {{count}} wrong answer or timeout in this session.', errorCount_other: 'This target note had {{count}} wrong answers or timeouts in this session.',
    noErrors: 'No target notes need priority attention in this session.', again: 'Practice again', done: 'Done',
    historyModule: 'Sight Reading', completedStatus: 'Completed', stoppedStatus: 'Ended early', historyTitle: '{{staff}} · {{key}}', historySettings: '{{pool}} · {{names}}',
    historyFacts: '{{settings}} · Completed {{completed}}/{{total}} · Correct {{correct}} / Wrong {{wrong}} / Timeout {{timeout}} · {{duration}}',
    durationSeconds_one: '{{count}} second', durationSeconds_other: '{{count}} seconds', durationMinutes_one: '{{count}} minute {{seconds}} s', durationMinutes_other: '{{count}} minutes {{seconds}} s',
    saveFailed: 'Local save failed', saveFailedHelp: 'Your practice results are retained. Try saving them on this device again.', retry: 'Retry'
  }
} as const
