export const themeManagementResources = {
  "zh-CN": {
    "importTitle": "导入主题包",
    "installTitle": "安装主题",
    "pickerHelp": "使用 Android 系统文件选择器选择 .pftheme",
    "close": "关闭",
    "choose": "选择主题包",
    "install": "安装",
    "update": "更新主题",
    "info": "主题信息",
    "theme": "主题",
    "subtitle": "副标题",
    "version": "版本",
    "signature": "签名",
    "verified": "已验证",
    "compatibility": "兼容范围",
    "name": "名称",
    "themeId": "themeId",
    "api": "Theme API",
    "signatureState": "签名状态",
    "keyId": "签名 keyId",
    "unsignedDebug": "未签名调试包",
    "installedAt": "安装日期",
    "verify": "验证主题",
    "verifying": "正在验证主题…",
    "intact": "主题完整",
    "verifyFailed": "主题验证失败",
    "remove": "删除主题",
    "confirmRemove": "确认删除",
    "confirmInactive": "确认删除？",
    "confirmActive": "确认删除（将先切换浅色）？",
    "processing": "正在处理主题…",
    "failed": "主题处理失败。",
    "recoveryTitle": "主题恢复",
    "recoveryDetail": "主题加载失败，正在恢复浅色主题…",
    "stages": {
      "READING": "正在读取",
      "VALIDATING": "正在验证",
      "CHECKING_SIGNATURE": "正在检查签名",
      "CHECKING_ASSETS": "正在检查素材",
      "READY_TO_INSTALL": "等待安装确认",
      "INSTALLING": "正在安装",
      "INSTALLED": "安装完成"
    },
    "errors": {
      "INVALID_THEME_PACKAGE": "不是有效主题包",
      "INVALID_MANIFEST": "不是有效主题包",
      "INVALID_THEME_SCHEMA": "主题文件损坏",
      "PACKAGE_TOO_LARGE": "主题包太大",
      "TOTAL_SIZE_EXCEEDED": "主题包解压后过大",
      "FILE_TOO_LARGE": "主题文件过大",
      "FORBIDDEN_FILE_TYPE": "主题包包含不允许的文件",
      "UNSAFE_PATH": "主题包路径不安全",
      "DUPLICATE_PATH": "主题包路径冲突",
      "SIGNATURE_INVALID": "主题包签名无效",
      "SIGNATURE_REQUIRED": "此版本要求主题包签名",
      "SIGNER_NOT_TRUSTED": "主题包签名者不受信任",
      "UNSIGNED_NOT_ALLOWED": "此版本不允许未签名主题包",
      "APP_VERSION_INCOMPATIBLE": "主题版本与当前应用不兼容",
      "THEME_VERSION_INCOMPATIBLE": "主题版本与当前应用不兼容",
      "THEME_API_UNSUPPORTED": "主题接口版本不兼容",
      "UNSUPPORTED_RECIPE": "主题使用了不支持的视觉配方",
      "THEME_FILE_MISSING": "主题文件缺失",
      "IMAGE_INVALID": "主题素材损坏",
      "CHECKSUM_MISMATCH": "主题文件校验失败",
      "INVALID_CHECKSUMS": "主题文件校验信息无效",
      "ALREADY_INSTALLED": "此版本已安装",
      "SAME_VERSION_DIFFERENT_PACKAGE": "同版本主题包内容不同，已拒绝覆盖",
      "DOWNGRADE_BLOCKED": "禁止降级安装主题",
      "PICKER_CANCELLED": "已取消选择",
      "PRODUCTION_TRUST_NOT_CONFIGURED": "正式主题信任配置尚未完成",
      "STORAGE_FULL": "设备空间不足",
      "INSTALL_FAILED": "主题安装失败",
      "THEME_LOAD_FAILED": "主题加载失败",
      "VERIFY_FAILED": "主题验证失败"
    }
  },
  "en": {
    "importTitle": "Import theme package",
    "installTitle": "Install theme",
    "pickerHelp": "Choose a .pftheme file with the Android file picker",
    "close": "Close",
    "choose": "Choose theme package",
    "install": "Install",
    "update": "Update theme",
    "info": "Theme information",
    "theme": "Theme",
    "subtitle": "Subtitle",
    "version": "Version",
    "signature": "Signature",
    "verified": "Verified",
    "compatibility": "Compatibility",
    "name": "Name",
    "themeId": "themeId",
    "api": "Theme API",
    "signatureState": "Signature status",
    "keyId": "Signing keyId",
    "unsignedDebug": "Unsigned debug package",
    "installedAt": "Installed on",
    "verify": "Verify theme",
    "verifying": "Verifying theme…",
    "intact": "Theme integrity verified",
    "verifyFailed": "The theme could not be verified.",
    "remove": "Delete theme",
    "confirmRemove": "Confirm deletion",
    "confirmInactive": "Delete this theme?",
    "confirmActive": "Delete this theme? The app will switch to Light first.",
    "processing": "Processing theme…",
    "failed": "The theme could not be processed.",
    "recoveryTitle": "Theme recovery",
    "recoveryDetail": "The theme could not be loaded. Restoring Light…",
    "stages": {
      "READING": "Reading",
      "VALIDATING": "Validating",
      "CHECKING_SIGNATURE": "Checking signature",
      "CHECKING_ASSETS": "Checking assets",
      "READY_TO_INSTALL": "Waiting for installation confirmation",
      "INSTALLING": "Installing",
      "INSTALLED": "Installation complete"
    },
    "errors": {
      "INVALID_THEME_PACKAGE": "The theme package is invalid.",
      "INVALID_MANIFEST": "The theme package is invalid.",
      "INVALID_THEME_SCHEMA": "The theme file is damaged.",
      "PACKAGE_TOO_LARGE": "The theme package is too large.",
      "TOTAL_SIZE_EXCEEDED": "The unpacked theme is too large.",
      "FILE_TOO_LARGE": "A theme file is too large.",
      "FORBIDDEN_FILE_TYPE": "The package contains a file type that is not allowed.",
      "UNSAFE_PATH": "The package contains an unsafe path.",
      "DUPLICATE_PATH": "The package contains conflicting paths.",
      "SIGNATURE_INVALID": "The theme signature is invalid.",
      "SIGNATURE_REQUIRED": "This app requires signed theme packages.",
      "SIGNER_NOT_TRUSTED": "The theme signer is not trusted.",
      "UNSIGNED_NOT_ALLOWED": "Unsigned theme packages are not allowed.",
      "APP_VERSION_INCOMPATIBLE": "This theme is not compatible with the app version.",
      "THEME_VERSION_INCOMPATIBLE": "This theme is not compatible with the app version.",
      "THEME_API_UNSUPPORTED": "This Theme API version is not supported.",
      "UNSUPPORTED_RECIPE": "This visual recipe is not supported.",
      "THEME_FILE_MISSING": "A required theme file is missing.",
      "IMAGE_INVALID": "A theme image is damaged.",
      "CHECKSUM_MISMATCH": "The theme checksum does not match.",
      "INVALID_CHECKSUMS": "The theme checksum information is invalid.",
      "ALREADY_INSTALLED": "This version is already installed.",
      "SAME_VERSION_DIFFERENT_PACKAGE": "A different package with the same version cannot replace this theme.",
      "DOWNGRADE_BLOCKED": "An older theme version cannot be installed.",
      "PICKER_CANCELLED": "File selection was cancelled.",
      "PRODUCTION_TRUST_NOT_CONFIGURED": "Production theme trust has not been configured.",
      "STORAGE_FULL": "The device is out of storage space.",
      "INSTALL_FAILED": "The theme could not be installed.",
      "THEME_LOAD_FAILED": "The theme could not be loaded.",
      "VERIFY_FAILED": "The theme could not be verified."
    }
  }
} as const
